DROP DATABASE IF EXISTS games_dev; 
CREATE DATABASE games_dev;

\c games_dev;

CREATE TABLE games (
id SERIAL PRIMARY KEY,
name TEXT NOT NULL,
is_favorite BOOLEAN NOT NULL,
genre TEXT DEFAULT NULL,
storyline TEXT DEFAULT NULL,
video_id VARCHAR(12) DEFAULT NULL,
image_id TEXT DEFAULT NULL,
cost FLOAT NOT NULL
); 